[package]
edition = "2021"
name = "food-generator2-cli"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
clap = {version = "4.5", features = ["derive"]}
food-generator2 = {path = "../core", features = ["compile"]}
