[package]
edition = "2021"
name = "food-generator2"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
bytes = "1.7"
deflate = "1.0"
inflate = "0.4"
nom = "7.1"
take_mut = "0.2"
unicode-ident = "1.0"

[features]
compile = []
compression = []
